---
- name: test serial strategies with Tower 
  hosts: all 
  serial: 1
  tasks:
    - name: print something 
      debug:
        msg: "Hello world"

    - name: print something 
      debug:
        msg: "goodbye world"
